Add CI for wasm (#4)

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -21,6 +21,8 @@ jobs:
       - uses: actions/cache@v2
         with:
           path: |
+            ~/.cargo/.crates.toml
+            ~/.cargo/.crates2.json
             ~/.cargo/bin/
             ~/.cargo/registry/index/
             ~/.cargo/registry/cache/
@@ -39,3 +41,43 @@ jobs:
         run: cargo test
         env:
           CARGO_INCREMENTAL: 0
+
+  build-wasm:
+    strategy:
+      matrix:
+        toolchain: [stable, nightly]
+        os: [ubuntu-latest]
+    runs-on: ${{ matrix.os }}
+    steps:
+      - uses: actions/checkout@v2
+      - uses: actions/cache@v2
+        with:
+          path: |
+            ~/.cargo/.crates.toml
+            ~/.cargo/.crates2.json
+            ~/.cargo/bin/
+            ~/.cargo/registry/index/
+            ~/.cargo/registry/cache/
+            ~/.cargo/git/db/
+            target/
+          key: ${{ runner.os }}-cargo-wasm-${{ matrix.toolchain }}-${{ hashFiles('**/Cargo.toml') }}
+      - uses: actions-rs/toolchain@v1
+        with:
+          toolchain: ${{ matrix.toolchain }}
+          target: wasm32-unknown-unknown
+          override: true
+      - name: Install Linux packages
+        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev libxcb-shape0-dev libxcb-xfixes0-dev
+        if: runner.os == 'linux'
+      - name: Install cargo make
+        run: cargo install cargo-make
+      - name: Build wasm
+        run: cargo make build-web
+        env:
+          CARGO_INCREMENTAL: 0
+      - name: Verify build
+        run: |
+          ls -la target/wasm32-unknown-unknown/debug/
+          [ -f target/wasm32-unknown-unknown/debug/libracity.wasm ] || (echo "Missing libracity.wasm" && exit 1)
+          s=`stat --printf='%s' target/wasm32-unknown-unknown/debug/libracity.wasm`
+          (($s > 200000000)) && echo "Size: $s bytes" || (echo "Size too small: $s bytes" && exit 2)
