Check .wasm file exists and is > 200MB

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -71,3 +71,9 @@ jobs:
         run: cargo make build-web
         env:
           CARGO_INCREMENTAL: 0
+      - name: Verify build
+        run: |
+          ls -la
+          [ -f target/wasm32-unknown-unknown/debug/libracity.wasm ] || (echo "Missing libracity.wasm" && exit 1)
+          s=`stat --printf='%s' target/wasm32-unknown-unknown/debug/libracity.wasm`
+          (($s > 200000000)) && echo "Size: $s bytes" || (echo "Size too small: $s bytes" && exit 2)
